# Generated by Django 4.2.15 on 2026-05-10 12:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='National ID must be 10 digits.', regex='^\\d{10}$')])),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must start with '05' and be 10 digits.", regex='^05\\d{8}$')])),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField()),
                ('doctors', models.ManyToManyField(related_name='patients', through='api.DoctorPatient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='XRay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='panoramic_xrays/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xrays', to='api.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_result_data', models.JSONField(help_text='Results coming from the AI model (YOLO).')),
                ('doctor_notes', models.TextField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False, help_text='Set to True when the doctor approves the report.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('xray', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='api.xray')),
            ],
        ),
        migrations.AddField(
            model_name='doctorpatient',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorpatient',
            unique_together={('doctor', 'patient')},
        ),
    ]
