# Generated by Django 6.0.4 on 2026-04-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_patient_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='xray',
            name='doctor_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xray',
            name='edited_report',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
