# Generated by Django 6.0.2 on 2026-04-07 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='رقم الجوال يجب أن يكون 10 أرقام ويبدأ بـ 05', regex='^05\\d{8}$')]),
        ),
    ]
